#!/usr/bin/env bash
# Mock cdxgen: mirrors cdxgen 10.x/11.x behaviour:
#  - resolves transitive deps (body-parser, qs, golang.org/x/net)
#  - marks dev deps with cdx:npm:package:development
#  - PyPI names PEP503-normalized (flask-login), Go versions without "v"
#  - nested metadata; licenses populated
export MOCK_VERSION="11.2.0"
. "$(dirname "$0")/_emit.sh" "$@"
cat > "$out" <<'JSON'
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.6",
  "metadata": { "tools": { "components": [ { "type": "application", "name": "cdxgen", "version": "11.2.0" } ] } },
  "components": [
    { "type": "library", "name": "express", "version": "4.19.2", "purl": "pkg:npm/express@4.19.2", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "body-parser", "version": "1.20.2", "purl": "pkg:npm/body-parser@1.20.2", "licenses": [ { "license": { "id": "MIT" } } ],
      "properties": [ { "name": "cdx:npm:package:path", "value": "node_modules/body-parser" } ] },
    { "type": "library", "name": "qs", "version": "6.11.0", "purl": "pkg:npm/qs@6.11.0", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "name": "lodash", "version": "4.17.21", "purl": "pkg:npm/lodash@4.17.21", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "group": "@babel", "name": "runtime", "version": "7.24.0", "purl": "pkg:npm/@babel/runtime@7.24.0", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "regenerator-runtime", "version": "0.14.1", "purl": "pkg:npm/regenerator-runtime@0.14.1", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "axios", "version": "1.6.0", "purl": "pkg:npm/axios@1.6.0", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "follow-redirects", "version": "1.15.3", "purl": "pkg:npm/follow-redirects@1.15.3", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "requests-toolkit-pro", "version": "1.2.0", "purl": "pkg:npm/requests-toolkit-pro@1.2.0" },
    { "type": "library", "name": "jest", "version": "29.7.0", "purl": "pkg:npm/jest@29.7.0", "scope": "optional",
      "properties": [ { "name": "cdx:npm:package:development", "value": "true" } ] },
    { "type": "library", "name": "eslint", "version": "8.57.0", "purl": "pkg:npm/eslint@8.57.0", "scope": "optional",
      "properties": [ { "name": "cdx:npm:package:development", "value": "true" } ] },

    { "type": "library", "name": "flask", "version": "3.0.2", "purl": "pkg:pypi/flask@3.0.2", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "name": "werkzeug", "version": "3.0.1", "purl": "pkg:pypi/werkzeug@3.0.1", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "name": "jinja2", "version": "3.1.3", "purl": "pkg:pypi/jinja2@3.1.3", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "name": "requests", "version": "2.31.0", "purl": "pkg:pypi/requests@2.31.0", "licenses": [ { "license": { "id": "Apache-2.0" } } ] },
    { "type": "library", "name": "urllib3", "version": "2.1.0", "purl": "pkg:pypi/urllib3@2.1.0", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "pyyaml", "version": "6.0.1", "purl": "pkg:pypi/pyyaml@6.0.1", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "flask-login", "version": "0.6.3", "purl": "pkg:pypi/flask-login@0.6.3", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "name": "cryptography", "version": "42.0.0", "purl": "pkg:pypi/cryptography@42.0.0", "licenses": [ { "expression": "Apache-2.0 OR BSD-3-Clause" } ] },

    { "type": "library", "group": "github.com/gorilla", "name": "mux", "version": "1.8.1", "purl": "pkg:golang/github.com/gorilla/mux@1.8.1", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "group": "golang.org/x", "name": "crypto", "version": "0.17.0", "purl": "pkg:golang/golang.org/x/crypto@0.17.0", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "group": "golang.org/x", "name": "net", "version": "0.10.0", "purl": "pkg:golang/golang.org/x/net@0.10.0", "licenses": [ { "license": { "id": "BSD-3-Clause" } } ] },
    { "type": "library", "group": "github.com/gin-gonic", "name": "gin", "version": "1.9.1", "purl": "pkg:golang/github.com/gin-gonic/gin@1.9.1", "licenses": [ { "license": { "id": "MIT" } } ] },
    { "type": "library", "group": "github.com/go-playground", "name": "validator", "version": "10.14.0", "purl": "pkg:golang/github.com/go-playground/validator/v10@10.14.0", "licenses": [ { "license": { "id": "MIT" } } ] }
  ]
}
JSON
